import 'package:flutter/material.dart';
import 'package:temaribet/model/lecture.dart';
import 'package:temaribet/model/note.dart';

class Topics with ChangeNotifier {
  List<Note> _notes = [
    Note(
      id: "1",
      noteTopics: "Atomic Structure",
      noteContent: [
        "Atomic Structure",
        "An atom is the smallest unit of matter that retains all of the chemical properties of an element. Atoms combine to form molecules, which then interact to form solids, gases, or liquids. For example, water is composed of hydrogen and oxygen atoms that have combined to form water molecules. Many biological processes are devoted to breaking down molecules into their component atoms so they can be reassembled into a more useful molecule.",
        "Atomic Particles",
        "Atoms consist of three basic particles: protons, electrons, and neutrons. The nucleus (center) of the atom contains the protons (positively charged) and the neutrons (no charge). The outermost regions of the atom are called electron shells and contain the electrons (negatively charged). Atoms have different properties based on the arrangement and number of their basic particles.",
        "Atomic Mass",
        "Protons and neutrons have approximately the same mass, about 1.67 × 10-24 grams. Scientists define this amount of mass as one atomic mass unit (amu) or one Dalton. Although similar in mass, protons are positively charged, while neutrons have no charge. Therefore, the number of neutrons in an atom contributes significantly to its mass, but not to its charge.",
        "Volume of Atoms",
        "Accounting for the sizes of protons, neutrons, and electrons, most of the volume of an atom—greater than 99 percent—is, in fact, empty space. Despite all this empty space, solid objects do not just pass through one another. The electrons that surround all atoms are negatively charged and cause atoms to repel one another, preventing atoms from occupying the same space. These intermolecular forces prevent you from falling through an object like your chair.",
        "Atomic Number",
        "Neutral atoms of an element contain an equal number of protons and electrons. The number of protons determines an element’s atomic number (Z) and distinguishes one element from another. For example, carbon’s atomic number (Z) is 6 because it has 6 protons. The number of neutrons can vary to produce isotopes, which are atoms of the same element that have different numbers of neutrons. The number of electrons can also be different in atoms of the same element, thus producing ions (charged atoms). For instance, iron, Fe, can exist in its neutral state, or in the +2 and +3  ionic states.",
        "Mass Number",
        "An element’s mass number (A) is the sum of the number of protons and the number of neutrons. The small contribution of mass from electrons is disregarded in calculating the mass number. This approximation of mass can be used to easily calculate how many neutrons an element has by simply subtracting the number of protons from the mass number. Protons and neutrons both weigh about one atomic mass unit or amu. Isotopes of the same element will have the same atomic number but different mass numbers.",
      ],
      courseId: "4",
    ),
    Note(
      id: "2",
      noteTopics: "Electrochemistry",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "3",
      noteTopics: "Units and Measurement",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "4",
      noteTopics: "Thermochemistry",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "5",
      noteTopics: "Chemical Bonding",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "6",
      noteTopics: "Periodic Table",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "7",
      noteTopics: "Equations and Stoichiometry",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "8",
      noteTopics: "Solutions and Mixtures",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "4",
    ),
    Note(
      id: "9",
      noteTopics: "Thermodynamics",
      noteContent: [
        "Introduction",
        "Thermodynamics is a science of the relationship between heat, work, temperature, and energy. In broad terms, thermodynamics deals with the transfer of energy from one place to another and from one form to another. The key concept is that heat is a form of energy corresponding to a definite amount of mechanical work.",
        "1.1. Thermal equilibrium and definition of temperature",
        """Atoms and Moles
        The term mole is used to represent large number of atoms or molecules just the way a dozen is used to represent 12 things. A dozen eggs means 12 eggs.

Moles of particles work similarly. One mole of Helium gas means 6.02×1023 particles of Helium gas. Or one mole of eggs would mean 6.02×1023 eggs. The number 6.02×1023 is called Avogadro’s number (NA). From the dozen analogy if there are ‘n’ moles of particles to know the total number of particles all we have to do is:
N=nNA where N- no. of particles
            n- no. of moles
            NA- Avogadro’s no.

One mole of water contains 6.02×1023 molecules of water. This means there are 6.02×1023 Oxygen atoms and 1.20×1024 Hydrogen atoms (2 Hydrogen atoms in each water molecule).

The dozen analogy works once more for the concept of molar mass. Three dozen eggs means 36(3×12). If the price of a dozen egg is 60 birr, the price of a single egg 5 birr (60/12).

Molar mass of a substance is the mass of one mole of that substance. To find the mass of each particle, all we have to do is to divide the molar mass by Avogadro’s no. i.e. ,

    mP=M/NA where mp-mass of one particle of a substance
                  M- molar mass of the substance
    The mass of n moles of a substance is:
            m=nM (like the price of 3 dozen eggs is 3*60=180 birr)

Temperature

We often associate the concept of temperature with how hot or cold an object feels. Our senses are, however, unreliable. Let say we have three bottles filled with water. A is ice, B is lukewarm and C is boiling. Relative to C, B is cold but relative to A, B is hot. Is B hot or cold?

So, we need a reliable measure of hotness and coldness hence Temperature. An important way to define temperature is using the particle model of matter. The particle model of matter is a way of visualizing what individual particles are doing inside a substance.

Particles of matter are always in random motion. In solids, they are vibrating. In liquids and gases, they are moving more freely. Consequently, particles collide with their neighbors. Because of this collision, energy is distributed throughout the substance.

Temperature is the measure of how fast, on average, the particles of that substance are moving. The faster the particles are vibrating, the higher the temperature of the substance is.

Thus, temperature can be defined as the measure of the average random kinetic energy of particles in a body.Suppose two objects, one hot and one cold, are in thermal contact. Energy is transferred from the hotter object to the colder object. For example, when hot water and cold water are mixed in a bath tub, energy is transferred form the hot water to the cold water. Eventually, they reach to some intermediate temperature.

We know from the particle model of matter, this is the case because the particles in the hotter body are moving faster than that of the colder body. First, the particles at the boundary collide and then through many collisions the energy is distributed throughout the bodies until then reach a point where there will not be any energy transfer between the two bodies. This situation is called thermal equilibrium. The net transfer of thermal energy from the hotter body to the colder body is called heating.

This is the only way that the word heat can be used. A body does not contain or possess heat.

The zeroth law of thermodynamics (the law of equilibrium)

It can be stated as:
If objects A and B are separately in thermal equilibrium with a third object C, then A and B are in thermal equilibrium with each other.

This is the way thermometers work and this law also gives us a way to define temperature as a property that determines whether an object is in thermal equilibrium with other objects. Two bodies that are in thermal equilibrium with each other are at the same temperature. Temperature thus dictates the direction of heat transfer. Heat flows from a body with a higher temperature to a body with a lower temperature.

Temperature scales
Fahrenheit scale:
This is a common temperature scale in everyday use in the United States. This scale sets the temperature of the ice point of water 32 F and the temperature of steam point at 212 F.

Celsius scale:
Defines the ice point of water (at atmospheric pressure) to be 0 oC and the steam point of water to be 100 oC.

Both of the above scales are based on assigning random melting and boiling points
associated with one particular substance, water, on one particular planet, Earth.

Kelvin scale:
This is a scale based on a true zero value of temperature. It sets -273.15 oC, the temperature at which all the random motion of particles in a substance cease, as its zero point, 0 K. The second reference temperature for this scale was chosen as the triple point of water. This is a single combination of temperature and pressure at which all the three states of water coexist in equilibrium. This point was defined to be 273.16 K.

The relationship between the kelvin and Celsius scale is given by:
  TK=TC+273.15
The Kelvin scale is also referred to as the absolute thermodynamic scale.

Caution:
If you encounter an equation that calls for a temperature T or that involves a ratio of temperatures, you MUST convert all temperatures to Kelvin. If an equation contains a change in temperature, using Celsius temperature will also work, but it is always safe to convert temperatures to the Kelvin scale.

Phase of matter
A phase of matter is when all the physical properties within a material are uniform.

State and phase of matter are closely related concepts. States of matter are based on some large scale properties of phases of matter. Look at the figure below
""",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "10",
      noteTopics: "Dynamics: Forces and Motion",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "11",
      noteTopics: "Impulse and Momentum",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "12",
      noteTopics: "Conservation of Energy",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "13",
      noteTopics: "Periodic and Simple Harmonic Motion",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "14",
      noteTopics: "Heat and Temperature",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "15",
      noteTopics: "Wave Energy",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "16",
      noteTopics: "Electricity and Electrical Energy",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "17",
      noteTopics: "Magnetism and Magnetic Force",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "18",
      noteTopics: "Electromagnetism and Electromagnets",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
    Note(
      id: "19",
      noteTopics: "Nature and Behavior of Light",
      noteContent: [
        "Introduction",
        "Electrochemistry is the study of chemical processes that cause electrons to move. This movement of electrons is called electricity, which can be generated by movements of electrons from one element to another in a reaction known as an oxidation-reduction (\"redox\") reaction.",
        "Cell EMF",
        "The electromotive force (EMF) is the maximum potential difference between two electrodes of a galvanic or voltaic cell. This quantity is related to the tendency for an element, a compound or an ion to acquire (i.e. gain) or release (lose) electrons.",
        "Electrolysis",
        "Chemical reactions in batteries or galvanic cells provide the driving force for electrons to struggle through loads. This is how chemical energy is transformed into electric energy. Electrolysis can be carried out in solutions or molten salts (liquid). Because the atoms and ions have to move physically, the medium has to be a fluid. The products, like the reactants in a galvanic cell, can be in a solid, liquid, or gas state.",
        "Half-Cell Reaction",
        "A half cell is one of the two electrodes in a galvanic cell or simple battery. For example, in the Zn−Cu battery, the two half cells make an oxidizing-reducing couple. Placing a piece of reactant in an electrolyte solution makes a half cell. Unless it is connected to another half cell via an electric conductor and salt bridge, no reaction will take place in a half cell.",
        "Nernst Equation",
        "Electrochemistry deals with cell potential as well as energy of chemical reactions. The energy of a chemical system drives the charges to move, and the driving force gives rise to the cell potential of a system called galvanic cell. The energy aspect is also related to the chemical equilibrium. All these relationships are tied together in the concept of the Nernst equation.",
      ],
      courseId: "2",
    ),
  ];
  List<Note> get notes {
    return [..._notes];
  }

  Note findById(String id) {
    return _notes.firstWhere((element) => element.id == id);
  }

  Iterable<Note> findByNoteId(String id) {
    return _notes.where((element) => element.courseId == id);
  }

  void addNote() {
    // _notes.add(value);
    notifyListeners();
  }
}
